services:
  app:
    restart: always
    build:
      context: ./.docker/php
    volumes:
      - ./:/var/www/
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - application-network
  db-test:
    image: mysql:8.0.25
    platform: linux/x86_64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3309:3306'
    environment:
      MYSQL_DATABASE: qop
      MYSQL_ROOT_PASSWORD: qop
      MYSQL_PASSWORD: qop
      MYSQL_USER: qop
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql-test:/docker-entrypoint-initdb.d
    networks:
      - application-network

networks:
  application-network:
    driver: bridge